name: MDC Workflow

on:
  workflow_dispatch:
    inputs:
      runner:
        description: 'Escolha um runner para seu JOB'
        required: true
        type: choice
        default: 'ubuntu-latest'
        options:
          - 'ubuntu-latest'
          - 'macos-latest'

jobs:

  build:
    runs-on: ${{ inputs.runner }}

    steps:
      - name: Checkout do Código
        uses: actions/checkout@v4

      - name: Executando no Runner
        run: echo "Executando um deploy usando um runner no input"